### ISSUE TITLE
Screensaver continues run even when the display is put to sleep

### ISSUE THREAD

**Issue by graysky2** [xbmc/screensavers.rsxs#9]
Can you modify your code to honor the power saving settings? For example, other screensavers cease to run (as judged by reduced cpu usage) after the display is in power savings mode (Settings>System>Power savings>Put display to sleep when idle).

Using the skyrocket saver as a test, it seems to run even when the display is off.

**Comment by notspiff** [comment]
hmm. i will investigate it time admitting (not this week likely - damn
deadlines at work). last time i dabbled in there (this is kodi core stuff),
it would go to 'slow' rendering, i.e. render at 5fps or something to keep
the app loop responsive once displays entered power saving to keep it
responsive to wakeup requests, while keeping cpu overhead low. could be
there's an update running on a separate thread in the rsxs code or the
likes.

**Comment by AlwinEsch** [comment]
As this issue now very old and very big changes comes become this issue closed.
